#!/bin/bash
set -e

if [ "$#" -ne 1 ]; then
    echo "This script is designed to be called by basilisk automatically"
    exit 1
fi

cd "$(dirname "${BASH_SOURCE[0]}")"

# CSS
mkdir -p $1/static/css

cat ../_static/css/reset.css \
    ../_static/css/style.css \
    > $1/static/css/main.css

cp -r ../_static/fonts $1/static
